<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Parish;
use Illuminate\Support\Facades\DB;

class ParishTableSeeder extends Seeder
{

    
    protected $parishesArray = [
        ['name' => 'Alto Orinoco','municipality_id' => '149','id_municipio' => '1'],
        ['name' => 'Huachamacare Acanaña','municipality_id' => '149','id_municipio' => '1'],
        ['name' => 'Marawaka Toky Shamanaña','municipality_id' => '149','id_municipio' => '1'],
        ['name' => 'Mavaka Mavaka','municipality_id' => '149','id_municipio' => '1'],
        ['name' => 'Sierra Parima Parimabé','municipality_id' => '149','id_municipio' => '1'],
        ['name' => 'Ucata Laja Lisa','municipality_id' => '755','id_municipio' => '2'],
        ['name' => 'Yapacana Macuruco','municipality_id' => '755','id_municipio' => '2'],
        ['name' => 'Caname Guarinuma','municipality_id' => '755','id_municipio' => '2'],
        ['name' => 'Fernando Girón Tovar','municipality_id' => '3508','id_municipio' => '3'],
        ['name' => 'Luis Alberto Gómez','municipality_id' => '3508','id_municipio' => '3'],
        ['name' => 'Pahueña Limón de Parhueña','municipality_id' => '3508','id_municipio' => '3'],
        ['name' => 'Platanillal Platanillal','municipality_id' => '3508','id_municipio' => '3'],
        ['name' => 'Samariapo','municipality_id' => '3582','id_municipio' => '4'],
        ['name' => 'Sipapo','municipality_id' => '3582','id_municipio' => '4'],
        ['name' => 'Munduapo','municipality_id' => '3582','id_municipio' => '4'],
        ['name' => 'Guayapo','municipality_id' => '3582','id_municipio' => '4'],
        ['name' => 'Alto Ventuari','municipality_id' => '3709','id_municipio' => '5'],
        ['name' => 'Medio Ventuari','municipality_id' => '3709','id_municipio' => '5'],
        ['name' => 'Bajo Ventuari','municipality_id' => '3709','id_municipio' => '5'],
        ['name' => 'Victorino','municipality_id' => '3853','id_municipio' => '6'],
        ['name' => 'Comunidad','municipality_id' => '3853','id_municipio' => '6'],
        ['name' => 'Casiquiare','municipality_id' => '3977','id_municipio' => '7'],
        ['name' => 'Cocuy','municipality_id' => '3977','id_municipio' => '7'],
        ['name' => 'San Carlos de Río Negro','municipality_id' => '3977','id_municipio' => '7'],
        ['name' => 'Solano','municipality_id' => '3977','id_municipio' => '7'],
        ['name' => 'Anaco','municipality_id' => '4103','id_municipio' => '8'],
        ['name' => 'San Joaquín','municipality_id' => '4103','id_municipio' => '8'],
        ['name' => 'Cachipo','municipality_id' => '4155','id_municipio' => '9'],
        ['name' => 'Aragua de Barcelona','municipality_id' => '4155','id_municipio' => '9'],
        ['name' => 'Lechería','municipality_id' => '161','id_municipio' => '11'],
        ['name' => 'El Morro','municipality_id' => '161','id_municipio' => '11'],
        ['name' => 'Puerto Píritu','municipality_id' => '173','id_municipio' => '12'],
        ['name' => 'San Miguel','municipality_id' => '173','id_municipio' => '12'],
        ['name' => 'Sucre','municipality_id' => '173','id_municipio' => '12'],
        ['name' => 'Valle de Guanape','municipality_id' => '184','id_municipio' => '13'],
        ['name' => 'Santa Bárbara','municipality_id' => '184','id_municipio' => '13'],
        ['name' => 'El Chaparro','municipality_id' => '241','id_municipio' => '14'],
        ['name' => 'Tomás Alfaro','municipality_id' => '241','id_municipio' => '14'],
        ['name' => 'Calatrava','municipality_id' => '241','id_municipio' => '14'],
        ['name' => 'Guanta','municipality_id' => '252','id_municipio' => '15'],
        ['name' => 'Chorrerón','municipality_id' => '252','id_municipio' => '15'],
        ['name' => 'Mamo','municipality_id' => '379','id_municipio' => '16'],
        ['name' => 'Soledad','municipality_id' => '379','id_municipio' => '16'],
        ['name' => 'Mapire','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'Piar','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'Santa Clara','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'San Diego de Cabrutica','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'Uverito','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'Zuata','municipality_id' => '646','id_municipio' => '17'],
        ['name' => 'Puerto La Cruz','municipality_id' => '675','id_municipio' => '18'],
        ['name' => 'Pozuelos','municipality_id' => '675','id_municipio' => '18'],
        ['name' => 'Onoto','municipality_id' => '702','id_municipio' => '19'],
        ['name' => 'San Pablo','municipality_id' => '702','id_municipio' => '19'],
        ['name' => 'San Mateo','municipality_id' => '756','id_municipio' => '20'],
        ['name' => 'El Carito','municipality_id' => '756','id_municipio' => '20'],
        ['name' => 'Santa Inés','municipality_id' => '756','id_municipio' => '20'],
        ['name' => 'La Romereña','municipality_id' => '756','id_municipio' => '20'],
        ['name' => 'Atapirire','municipality_id' => '784','id_municipio' => '21'],
        ['name' => 'Boca del Pao','municipality_id' => '784','id_municipio' => '21'],
        ['name' => 'El Pao','municipality_id' => '784','id_municipio' => '21'],
        ['name' => 'Pariaguán','municipality_id' => '784','id_municipio' => '21'],
        ['name' => 'Cantaura','municipality_id' => '785','id_municipio' => '22'],
        ['name' => 'Libertador','municipality_id' => '785','id_municipio' => '22'],
        ['name' => 'Santa Rosa','municipality_id' => '785','id_municipio' => '22'],
        ['name' => 'Urica','municipality_id' => '785','id_municipio' => '22'],
        ['name' => 'Píritu','municipality_id' => '3268','id_municipio' => '23'],
        ['name' => 'San Francisco','municipality_id' => '3268','id_municipio' => '23'],
        ['name' => 'San José de Guanipa','municipality_id' => '3309','id_municipio' => '24'],
        ['name' => 'Boca de Uchire','municipality_id' => '3314','id_municipio' => '25'],
        ['name' => 'Boca de Chávez','municipality_id' => '3314','id_municipio' => '25'],
        ['name' => 'Pueblo Nuevo','municipality_id' => '3433','id_municipio' => '26'],
        ['name' => 'Santa Ana','municipality_id' => '3433','id_municipio' => '26'],
        ['name' => 'Bergantín','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'Caigua','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'El Carmen','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'El Pilar','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'Naricual','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'San Crsitóbal','municipality_id' => '3444','id_municipio' => '27'],
        ['name' => 'Edmundo Barrios','municipality_id' => '3486','id_municipio' => '28'],
        ['name' => 'Miguel Otero Silva','municipality_id' => '3486','id_municipio' => '28'],
        ['name' => 'Achaguas','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'Apurito','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'El Yagual','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'Guachara','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'Mucuritas','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'Queseras del medio','municipality_id' => '3497','id_municipio' => '29'],
        ['name' => 'Biruaca','municipality_id' => '3509','id_municipio' => '30'],
        ['name' => 'Bruzual','municipality_id' => '3520','id_municipio' => '31'],
        ['name' => 'Mantecal','municipality_id' => '3520','id_municipio' => '31'],
        ['name' => 'Quintero','municipality_id' => '3520','id_municipio' => '31'],
        ['name' => 'Rincón Hondo','municipality_id' => '3520','id_municipio' => '31'],
        ['name' => 'San Vicente','municipality_id' => '3520','id_municipio' => '31'],
        ['name' => 'Guasdualito','municipality_id' => '3522','id_municipio' => '32'],
        ['name' => 'Aramendi','municipality_id' => '3522','id_municipio' => '32'],
        ['name' => 'El Amparo','municipality_id' => '3522','id_municipio' => '32'],
        ['name' => 'San Camilo','municipality_id' => '3522','id_municipio' => '32'],
        ['name' => 'Urdaneta','municipality_id' => '3522','id_municipio' => '32'],
        ['name' => 'San Juan de Payara','municipality_id' => '3523','id_municipio' => '33'],
        ['name' => 'Codazzi','municipality_id' => '3523','id_municipio' => '33'],
        ['name' => 'Cunaviche','municipality_id' => '3523','id_municipio' => '33'],
        ['name' => 'Elorza','municipality_id' => '3524','id_municipio' => '34'],
        ['name' => 'La Trinidad','municipality_id' => '3524','id_municipio' => '34'],
        ['name' => 'San Fernando','municipality_id' => '3534','id_municipio' => '35'],
        ['name' => 'El Recreo','municipality_id' => '3534','id_municipio' => '35'],
        ['name' => 'Peñalver','municipality_id' => '3534','id_municipio' => '35'],
        ['name' => 'San Rafael de Atamaica','municipality_id' => '3534','id_municipio' => '35'],
        ['name' => 'Pedro José Ovalles','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Joaquín Crespo','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'José Casanova Godoy','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Madre María de San José','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Andrés Eloy Blanco','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Los Tacarigua','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Las Delicias','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Choroní','municipality_id' => '3545','id_municipio' => '36'],
        ['name' => 'Bolívar','municipality_id' => '3556','id_municipio' => '37'],
        ['name' => 'Camatagua','municipality_id' => '3567','id_municipio' => '38'],
        ['name' => 'Carmen de Cura','municipality_id' => '3567','id_municipio' => '38'],
        ['name' => 'Santa Rita','municipality_id' => '3578','id_municipio' => '39'],
        ['name' => 'Francisco de Miranda','municipality_id' => '3578','id_municipio' => '39'],
        ['name' => 'Moseñor Feliciano González','municipality_id' => '3578','id_municipio' => '39'],
        ['name' => 'Santa Cruz','municipality_id' => '3583','id_municipio' => '40'],
        ['name' => 'José Félix Ribas','municipality_id' => '3587','id_municipio' => '41'],
        ['name' => 'Castor Nieves Ríos','municipality_id' => '3587','id_municipio' => '41'],
        ['name' => 'Las Guacamayas','municipality_id' => '3587','id_municipio' => '41'],
        ['name' => 'Pao de Zárate','municipality_id' => '3587','id_municipio' => '41'],
        ['name' => 'Zuata','municipality_id' => '3587','id_municipio' => '41'],
        ['name' => 'José Rafael Revenga','municipality_id' => '3634','id_municipio' => '42'],
        ['name' => 'Palo Negro','municipality_id' => '3635','id_municipio' => '43'],
        ['name' => 'San Martín de Porres','municipality_id' => '3635','id_municipio' => '43'],
        ['name' => 'El Limón','municipality_id' => '3636','id_municipio' => '44'],
        ['name' => 'Caña de Azúcar','municipality_id' => '3636','id_municipio' => '44'],
        ['name' => 'Ocumare de la Costa','municipality_id' => '3661','id_municipio' => '45'],
        ['name' => 'San Casimiro','municipality_id' => '3672','id_municipio' => '46'],
        ['name' => 'Güiripa','municipality_id' => '3672','id_municipio' => '46'],
        ['name' => 'Ollas de Caramacate','municipality_id' => '3672','id_municipio' => '46'],
        ['name' => 'Valle Morín','municipality_id' => '3672','id_municipio' => '46'],
        ['name' => 'San Sebastían','municipality_id' => '3676','id_municipio' => '47'],
        ['name' => 'Turmero','municipality_id' => '3707','id_municipio' => '48'],
        ['name' => 'Arevalo Aponte','municipality_id' => '3707','id_municipio' => '48'],
        ['name' => 'Chuao','municipality_id' => '3707','id_municipio' => '48'],
        ['name' => 'Samán de Güere','municipality_id' => '3707','id_municipio' => '48'],
        ['name' => 'Alfredo Pacheco Miranda','municipality_id' => '3707','id_municipio' => '48'],
        ['name' => 'Santos Michelena','municipality_id' => '3708','id_municipio' => '49'],
        ['name' => 'Tiara','municipality_id' => '3708','id_municipio' => '49'],
        ['name' => 'Cagua','municipality_id' => '3710','id_municipio' => '50'],
        ['name' => 'Bella Vista','municipality_id' => '3710','id_municipio' => '50'],
        ['name' => 'Tovar','municipality_id' => '3740','id_municipio' => '51'],
        ['name' => 'Urdaneta','municipality_id' => '3741','id_municipio' => '52'],
        ['name' => 'Las Peñitas','municipality_id' => '3741','id_municipio' => '52'],
        ['name' => 'San Francisco de Cara','municipality_id' => '3741','id_municipio' => '52'],
        ['name' => 'Taguay','municipality_id' => '3741','id_municipio' => '52'],
        ['name' => 'Zamora','municipality_id' => '3806','id_municipio' => '53'],
        ['name' => 'Magdaleno','municipality_id' => '3806','id_municipio' => '53'],
        ['name' => 'San Francisco de Asís','municipality_id' => '3806','id_municipio' => '53'],
        ['name' => 'Valles de Tucutunemo','municipality_id' => '3806','id_municipio' => '53'],
        ['name' => 'Augusto Mijares','municipality_id' => '3806','id_municipio' => '53'],
        ['name' => 'Sabaneta','municipality_id' => '3807','id_municipio' => '54'],
        ['name' => 'Juan Antonio Rodríguez Domínguez','municipality_id' => '3807','id_municipio' => '54'],
        ['name' => 'El Cantón','municipality_id' => '3848','id_municipio' => '55'],
        ['name' => 'Santa Cruz de Guacas','municipality_id' => '3848','id_municipio' => '55'],
        ['name' => 'Puerto Vivas','municipality_id' => '3848','id_municipio' => '55'],
        ['name' => 'Ticoporo','municipality_id' => '3849','id_municipio' => '56'],
        ['name' => 'Nicolás Pulido','municipality_id' => '3849','id_municipio' => '56'],
        ['name' => 'Andrés Bello','municipality_id' => '3849','id_municipio' => '56'],
        ['name' => 'Arismendi','municipality_id' => '3850','id_municipio' => '57'],
        ['name' => 'Guadarrama','municipality_id' => '3850','id_municipio' => '57'],
        ['name' => 'La Unión','municipality_id' => '3850','id_municipio' => '57'],
        ['name' => 'San Antonio','municipality_id' => '3850','id_municipio' => '57'],
        ['name' => 'Barinas','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Alberto Arvelo Larriva','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'San Silvestre','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Santa Inés','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Santa Lucía','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Torunos','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'El Carmen','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Rómulo Betancourt','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Corazón de Jesús','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Ramón Ignacio Méndez','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Alto Barinas','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Manuel Palacio Fajardo','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Juan Antonio Rodríguez Domínguez','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Dominga Ortiz de Páez','municipality_id' => '3851','id_municipio' => '58'],
        ['name' => 'Barinitas','municipality_id' => '3852','id_municipio' => '59'],
        ['name' => 'Altamira de Cáceres','municipality_id' => '3852','id_municipio' => '59'],
        ['name' => 'Calderas','municipality_id' => '3852','id_municipio' => '59'],
        ['name' => 'Barrancas','municipality_id' => '3854','id_municipio' => '60'],
        ['name' => 'El Socorro','municipality_id' => '3854','id_municipio' => '60'],
        ['name' => 'Mazparrito','municipality_id' => '3854','id_municipio' => '60'],
        ['name' => 'Santa Bárbara','municipality_id' => '3855','id_municipio' => '61'],
        ['name' => 'Pedro Briceño Méndez','municipality_id' => '3855','id_municipio' => '61'],
        ['name' => 'Ramón Ignacio Méndez','municipality_id' => '3855','id_municipio' => '61'],
        ['name' => 'José Ignacio del Pumar','municipality_id' => '3855','id_municipio' => '61'],
        ['name' => 'Obispos','municipality_id' => '3856','id_municipio' => '62'],
        ['name' => 'Guasimitos','municipality_id' => '3856','id_municipio' => '62'],
        ['name' => 'El Real','municipality_id' => '3856','id_municipio' => '62'],
        ['name' => 'La Luz','municipality_id' => '3856','id_municipio' => '62'],
        ['name' => 'Ciudad Bolívia','municipality_id' => '3857','id_municipio' => '63'],
        ['name' => 'José Ignacio Briceño','municipality_id' => '3857','id_municipio' => '63'],
        ['name' => 'José Félix Ribas','municipality_id' => '3857','id_municipio' => '63'],
        ['name' => 'Páez','municipality_id' => '3857','id_municipio' => '63'],
        ['name' => 'Libertad','municipality_id' => '3870','id_municipio' => '64'],
        ['name' => 'Dolores','municipality_id' => '3870','id_municipio' => '64'],
        ['name' => 'Santa Rosa','municipality_id' => '3870','id_municipio' => '64'],
        ['name' => 'Palacio Fajardo','municipality_id' => '3870','id_municipio' => '64'],
        ['name' => 'Ciudad de Nutrias','municipality_id' => '3871','id_municipio' => '65'],
        ['name' => 'El Regalo','municipality_id' => '3871','id_municipio' => '65'],
        ['name' => 'Puerto Nutrias','municipality_id' => '3871','id_municipio' => '65'],
        ['name' => 'Santa Catalina','municipality_id' => '3871','id_municipio' => '65'],
        ['name' => 'Cachamay','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Chirica','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Dalla Costa','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Once de Abril','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Simón Bolívar','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Unare','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Universidad','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Vista al Sol','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Pozo Verde','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Yocoima','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => '5 de Julio','municipality_id' => '3872','id_municipio' => '66'],
        ['name' => 'Cedeño','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'Altagracia','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'Ascensión Farreras','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'Guaniamo','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'La Urbana','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'Pijiguaos','municipality_id' => '3887','id_municipio' => '67'],
        ['name' => 'El Callao','municipality_id' => '3888','id_municipio' => '68'],
        ['name' => 'Gran Sabana','municipality_id' => '3976','id_municipio' => '69'],
        ['name' => 'Ikabarú','municipality_id' => '3976','id_municipio' => '69'],
        ['name' => 'Catedral','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Zea','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Orinoco','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'José Antonio Páez','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Marhuanta','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Agua Salada','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Vista Hermosa','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'La Sabanita','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Panapana','municipality_id' => '3978','id_municipio' => '70'],
        ['name' => 'Andrés Eloy Blanco','municipality_id' => '4005','id_municipio' => '71'],
        ['name' => 'Pedro Cova','municipality_id' => '4005','id_municipio' => '71'],
        ['name' => 'Raúl Leoni','municipality_id' => '4006','id_municipio' => '72'],
        ['name' => 'Barceloneta','municipality_id' => '4006','id_municipio' => '72'],
        ['name' => 'Santa Bárbara','municipality_id' => '4006','id_municipio' => '72'],
        ['name' => 'San Francisco','municipality_id' => '4006','id_municipio' => '72'],
        ['name' => 'Roscio','municipality_id' => '4007','id_municipio' => '73'],
        ['name' => 'Salóm','municipality_id' => '4007','id_municipio' => '73'],
        ['name' => 'Sifontes','municipality_id' => '4055','id_municipio' => '74'],
        ['name' => 'Dalla Costa','municipality_id' => '4055','id_municipio' => '74'],
        ['name' => 'San Isidro','municipality_id' => '4055','id_municipio' => '74'],
        ['name' => 'Sucre','municipality_id' => '4056','id_municipio' => '75'],
        ['name' => 'Aripao','municipality_id' => '4056','id_municipio' => '75'],
        ['name' => 'Guarataro','municipality_id' => '4056','id_municipio' => '75'],
        ['name' => 'Las Majadas','municipality_id' => '4056','id_municipio' => '75'],
        ['name' => 'Moitaco','municipality_id' => '4056','id_municipio' => '75'],
        ['name' => 'Padre Pedro Chien','municipality_id' => '4057','id_municipio' => '76'],
        ['name' => 'Río Grande','municipality_id' => '4057','id_municipio' => '76'],
        ['name' => 'Bejuma','municipality_id' => '4100','id_municipio' => '77'],
        ['name' => 'Canoabo','municipality_id' => '4100','id_municipio' => '77'],
        ['name' => 'Simón Bolívar','municipality_id' => '4100','id_municipio' => '77'],
        ['name' => 'Güigüe','municipality_id' => '4101','id_municipio' => '78'],
        ['name' => 'Carabobo','municipality_id' => '4101','id_municipio' => '78'],
        ['name' => 'Tacarigua','municipality_id' => '4101','id_municipio' => '78'],
        ['name' => 'Mariara','municipality_id' => '4102','id_municipio' => '79'],
        ['name' => 'Aguas Calientes','municipality_id' => '4102','id_municipio' => '79'],
        ['name' => 'Ciudad Alianza','municipality_id' => '4104','id_municipio' => '80'],
        ['name' => 'Guacara','municipality_id' => '4104','id_municipio' => '80'],
        ['name' => 'Yagua','municipality_id' => '4104','id_municipio' => '80'],
        ['name' => 'Morón','municipality_id' => '4105','id_municipio' => '81'],
        ['name' => 'Yagua','municipality_id' => '4105','id_municipio' => '81'],
        ['name' => 'Tocuyito','municipality_id' => '4113','id_municipio' => '82'],
        ['name' => 'Independencia','municipality_id' => '4113','id_municipio' => '82'],
        ['name' => 'Los Guayos','municipality_id' => '4114','id_municipio' => '83'],
        ['name' => 'Miranda','municipality_id' => '4115','id_municipio' => '84'],
        ['name' => 'Montalbán','municipality_id' => '4116','id_municipio' => '85'],
        ['name' => 'Naguanagua','municipality_id' => '4136','id_municipio' => '86'],
        ['name' => 'Bartolomé Salóm','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Democracia','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Fraternidad','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Goaigoaza','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Juan José Flores','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Unión','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Borburata','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'Patanemo','municipality_id' => '4150','id_municipio' => '87'],
        ['name' => 'San Diego','municipality_id' => '4151','id_municipio' => '88'],
        ['name' => 'San Joaquín','municipality_id' => '4154','id_municipio' => '89'],
        ['name' => 'Candelaria','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Catedral','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'El Socorro','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Miguel Peña','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Rafael Urdaneta','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'San Blas','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'San José','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Santa Rosa','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Negro Primero','municipality_id' => '4156','id_municipio' => '90'],
        ['name' => 'Cojedes','municipality_id' => '4157','id_municipio' => '91'],
        ['name' => 'Juan de Mata Suárez','municipality_id' => '4157','id_municipio' => '91'],
        ['name' => 'Tinaquillo','municipality_id' => '4169','id_municipio' => '92'],
        ['name' => 'El Baúl','municipality_id' => '4170','id_municipio' => '93'],
        ['name' => 'Sucre','municipality_id' => '4170','id_municipio' => '93'],
        ['name' => 'La Aguadita','municipality_id' => '4171','id_municipio' => '94'],
        ['name' => 'Macapo','municipality_id' => '4171','id_municipio' => '94'],
        ['name' => 'El Pao','municipality_id' => '4181','id_municipio' => '95'],
        ['name' => 'El Amparo','municipality_id' => '4186','id_municipio' => '96'],
        ['name' => 'Libertad de Cojedes','municipality_id' => '4186','id_municipio' => '96'],
        ['name' => 'Rómulo Gallegos','municipality_id' => '4187','id_municipio' => '97'],
        ['name' => 'San Carlos de Austria','municipality_id' => '4194','id_municipio' => '98'],
        ['name' => 'Juan Ángel Bravo','municipality_id' => '4194','id_municipio' => '98'],
        ['name' => 'Manuel Manrique','municipality_id' => '4194','id_municipio' => '98'],
        ['name' => 'General en Jefe José Laurencio Silva','municipality_id' => '4195','id_municipio' => '99'],
        ['name' => 'Curiapo','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Almirante Luis Brión','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Francisco Aniceto Lugo','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Manuel Renaud','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Padre Barral','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Santos de Abelgas','municipality_id' => '151','id_municipio' => '100'],
        ['name' => 'Imataca','municipality_id' => '152','id_municipio' => '101'],
        ['name' => 'Cinco de Julio','municipality_id' => '152','id_municipio' => '101'],
        ['name' => 'Juan Bautista Arismendi','municipality_id' => '152','id_municipio' => '101'],
        ['name' => 'Manuel Piar','municipality_id' => '152','id_municipio' => '101'],
        ['name' => 'Rómulo Gallegos','municipality_id' => '152','id_municipio' => '101'],
        ['name' => 'Pedernales','municipality_id' => '153','id_municipio' => '102'],
        ['name' => 'Luis Beltrán Prieto Figueroa','municipality_id' => '153','id_municipio' => '102'],
        ['name' => 'San José (Delta Amacuro)','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'José Vidal Marcano','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Juan Millán','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Leonardo Ruíz Pineda','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Mariscal Antonio José de Sucre','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Monseñor Argimiro García','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'San Rafael (Delta Amacuro)','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Virgen del Valle','municipality_id' => '154','id_municipio' => '103'],
        ['name' => 'Clarines','municipality_id' => '150','id_municipio' => '10'],
        ['name' => 'Guanape','municipality_id' => '150','id_municipio' => '10'],
        ['name' => 'Sabana de Uchire','municipality_id' => '150','id_municipio' => '10'],
        ['name' => 'Capadare','municipality_id' => '155','id_municipio' => '104'],
        ['name' => 'La Pastora','municipality_id' => '155','id_municipio' => '104'],
        ['name' => 'Libertador','municipality_id' => '155','id_municipio' => '104'],
        ['name' => 'San Juan de los Cayos','municipality_id' => '155','id_municipio' => '104'],
        ['name' => 'Aracua','municipality_id' => '156','id_municipio' => '105'],
        ['name' => 'La Peña','municipality_id' => '156','id_municipio' => '105'],
        ['name' => 'San Luis','municipality_id' => '156','id_municipio' => '105'],
        ['name' => 'Bariro','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Borojó','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Capatárida','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Guajiro','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Seque','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Zazárida','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Valle de Eroa','municipality_id' => '157','id_municipio' => '106'],
        ['name' => 'Cacique Manaure','municipality_id' => '158','id_municipio' => '107'],
        ['name' => 'Norte','municipality_id' => '159','id_municipio' => '108'],
        ['name' => 'Carirubana','municipality_id' => '159','id_municipio' => '108'],
        ['name' => 'Santa Ana','municipality_id' => '159','id_municipio' => '108'],
        ['name' => 'Urbana Punta Cardón','municipality_id' => '159','id_municipio' => '108'],
        ['name' => 'La Vela de Coro','municipality_id' => '160','id_municipio' => '109'],
        ['name' => 'Acurigua','municipality_id' => '160','id_municipio' => '109'],
        ['name' => 'Guaibacoa','municipality_id' => '160','id_municipio' => '109'],
        ['name' => 'Las Calderas','municipality_id' => '160','id_municipio' => '109'],
        ['name' => 'Macoruca','municipality_id' => '160','id_municipio' => '109'],
        ['name' => 'Dabajuro','municipality_id' => '162','id_municipio' => '110'],
        ['name' => 'Agua Clara','municipality_id' => '164','id_municipio' => '111'],
        ['name' => 'Avaria','municipality_id' => '164','id_municipio' => '111'],
        ['name' => 'Pedregal','municipality_id' => '164','id_municipio' => '111'],
        ['name' => 'Piedra Grande','municipality_id' => '164','id_municipio' => '111'],
        ['name' => 'Purureche','municipality_id' => '164','id_municipio' => '111'],
        ['name' => 'Adaure','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Adícora','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Baraived','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Buena Vista','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Jadacaquiva','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'El Vínculo','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'El Hato','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Moruy','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Pueblo Nuevo','municipality_id' => '165','id_municipio' => '112'],
        ['name' => 'Agua Larga','municipality_id' => '166','id_municipio' => '113'],
        ['name' => 'El Paují','municipality_id' => '166','id_municipio' => '113'],
        ['name' => 'Independencia','municipality_id' => '166','id_municipio' => '113'],
        ['name' => 'Mapararí','municipality_id' => '166','id_municipio' => '113'],
        ['name' => 'Agua Linda','municipality_id' => '167','id_municipio' => '114'],
        ['name' => 'Araurima','municipality_id' => '167','id_municipio' => '114'],
        ['name' => 'Jacura','municipality_id' => '167','id_municipio' => '114'],
        ['name' => 'Tucacas','municipality_id' => '168','id_municipio' => '115'],
        ['name' => 'Boca de Aroa','municipality_id' => '168','id_municipio' => '115'],
        ['name' => 'Los Taques','municipality_id' => '169','id_municipio' => '116'],
        ['name' => 'Judibana','municipality_id' => '169','id_municipio' => '116'],
        ['name' => 'Mene de Mauroa','municipality_id' => '170','id_municipio' => '117'],
        ['name' => 'San Félix','municipality_id' => '170','id_municipio' => '117'],
        ['name' => 'Casigua','municipality_id' => '170','id_municipio' => '117'],
        ['name' => 'Guzmán Guillermo','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'Mitare','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'Río Seco','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'Sabaneta','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'San Antonio','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'San Gabriel','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'Santa Ana','municipality_id' => '171','id_municipio' => '118'],
        ['name' => 'Boca del Tocuyo','municipality_id' => '172','id_municipio' => '119'],
        ['name' => 'Chichiriviche','municipality_id' => '172','id_municipio' => '119'],
        ['name' => 'Tocuyo de la Costa','municipality_id' => '172','id_municipio' => '119'],
        ['name' => 'Palmasola','municipality_id' => '174','id_municipio' => '120'],
        ['name' => 'Cabure','municipality_id' => '175','id_municipio' => '121'],
        ['name' => 'Colina','municipality_id' => '175','id_municipio' => '121'],
        ['name' => 'Curimagua','municipality_id' => '175','id_municipio' => '121'],
        ['name' => 'San José de la Costa','municipality_id' => '176','id_municipio' => '122'],
        ['name' => 'Píritu','municipality_id' => '176','id_municipio' => '122'],
        ['name' => 'San Francisco','municipality_id' => '177','id_municipio' => '123'],
        ['name' => 'Sucre','municipality_id' => '178','id_municipio' => '124'],
        ['name' => 'Pecaya','municipality_id' => '178','id_municipio' => '124'],
        ['name' => 'Tocópero','municipality_id' => '179','id_municipio' => '125'],
        ['name' => 'El Charal','municipality_id' => '180','id_municipio' => '126'],
        ['name' => 'Las Vegas del Tuy','municipality_id' => '180','id_municipio' => '126'],
        ['name' => 'Santa Cruz de Bucaral','municipality_id' => '180','id_municipio' => '126'],
        ['name' => 'Bruzual','municipality_id' => '181','id_municipio' => '127'],
        ['name' => 'Urumaco','municipality_id' => '181','id_municipio' => '127'],
        ['name' => 'Puerto Cumarebo','municipality_id' => '182','id_municipio' => '128'],
        ['name' => 'La Ciénaga','municipality_id' => '182','id_municipio' => '128'],
        ['name' => 'La Soledad','municipality_id' => '182','id_municipio' => '128'],
        ['name' => 'Pueblo Cumarebo','municipality_id' => '182','id_municipio' => '128'],
        ['name' => 'Zazárida','municipality_id' => '182','id_municipio' => '128'],
        ['name' => 'Churuguara','municipality_id' => '166','id_municipio' => '113'],
        ['name' => 'Camaguán','municipality_id' => '183','id_municipio' => '129'],
        ['name' => 'Puerto Miranda','municipality_id' => '183','id_municipio' => '129'],
        ['name' => 'Uverito','municipality_id' => '183','id_municipio' => '129'],
        ['name' => 'Chaguaramas','municipality_id' => '185','id_municipio' => '130'],
        ['name' => 'El Socorro','municipality_id' => '193','id_municipio' => '131'],
        ['name' => 'Tucupido','municipality_id' => '197','id_municipio' => '132'],
        ['name' => 'San Rafael de Laya','municipality_id' => '197','id_municipio' => '132'],
        ['name' => 'Altagracia de Orituco','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'San Rafael de Orituco','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'San Francisco Javier de Lezama','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'Paso Real de Macaira','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'Carlos Soublette','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'San Francisco de Macaira','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'Libertad de Orituco','municipality_id' => '203','id_municipio' => '133'],
        ['name' => 'Cantaclaro','municipality_id' => '205','id_municipio' => '134'],
        ['name' => 'San Juan de los Morros','municipality_id' => '205','id_municipio' => '134'],
        ['name' => 'Parapara','municipality_id' => '205','id_municipio' => '134'],
        ['name' => 'El Sombrero','municipality_id' => '214','id_municipio' => '135'],
        ['name' => 'Sosa','municipality_id' => '214','id_municipio' => '135'],
        ['name' => 'Las Mercedes','municipality_id' => '217','id_municipio' => '136'],
        ['name' => 'Cabruta','municipality_id' => '217','id_municipio' => '136'],
        ['name' => 'Santa Rita de Manapire','municipality_id' => '217','id_municipio' => '136'],
        ['name' => 'Valle de la Pascua','municipality_id' => '230','id_municipio' => '137'],
        ['name' => 'Espino','municipality_id' => '230','id_municipio' => '137'],
        ['name' => 'San José de Unare','municipality_id' => '234','id_municipio' => '138'],
        ['name' => 'Zaraza','municipality_id' => '234','id_municipio' => '138'],
        ['name' => 'San José de Tiznados','municipality_id' => '240','id_municipio' => '139'],
        ['name' => 'San Francisco de Tiznados','municipality_id' => '240','id_municipio' => '139'],
        ['name' => 'San Lorenzo de Tiznados','municipality_id' => '240','id_municipio' => '139'],
        ['name' => 'Ortiz','municipality_id' => '240','id_municipio' => '139'],
        ['name' => 'Guayabal','municipality_id' => '242','id_municipio' => '140'],
        ['name' => 'Cazorla','municipality_id' => '242','id_municipio' => '140'],
        ['name' => 'San José de Guaribe','municipality_id' => '243','id_municipio' => '141'],
        ['name' => 'Uveral','municipality_id' => '243','id_municipio' => '141'],
        ['name' => 'Santa María de Ipire','municipality_id' => '244','id_municipio' => '142'],
        ['name' => 'Altamira','municipality_id' => '244','id_municipio' => '142'],
        ['name' => 'El Calvario','municipality_id' => '245','id_municipio' => '143'],
        ['name' => 'El Rastro','municipality_id' => '245','id_municipio' => '143'],
        ['name' => 'Guardatinajas','municipality_id' => '245','id_municipio' => '143'],
        ['name' => 'Capital Urbana Calabozo','municipality_id' => '245','id_municipio' => '143'],
        ['name' => 'Quebrada Honda de Guache','municipality_id' => '246','id_municipio' => '144'],
        ['name' => 'Pío Tamayo','municipality_id' => '246','id_municipio' => '144'],
        ['name' => 'Yacambú','municipality_id' => '246','id_municipio' => '144'],
        ['name' => 'Fréitez','municipality_id' => '247','id_municipio' => '145'],
        ['name' => 'José María Blanco','municipality_id' => '247','id_municipio' => '145'],
        ['name' => 'Catedral','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Concepción','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'El Cují','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Juan de Villegas','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Santa Rosa','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Tamaca','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Unión','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Aguedo Felipe Alvarado','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Buena Vista','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Juárez','municipality_id' => '248','id_municipio' => '146'],
        ['name' => 'Juan Bautista Rodríguez','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Cuara','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Diego de Lozada','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Paraíso de San José','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'San Miguel','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Tintorero','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'José Bernardo Dorante','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Coronel Mariano Peraza ','municipality_id' => '249','id_municipio' => '147'],
        ['name' => 'Bolívar','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Anzoátegui','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Guarico','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Hilario Luna y Luna','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Humocaro Alto','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Humocaro Bajo','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'La Candelaria','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Morán','municipality_id' => '250','id_municipio' => '148'],
        ['name' => 'Cabudare','municipality_id' => '251','id_municipio' => '149'],
        ['name' => 'José Gregorio Bastidas','municipality_id' => '251','id_municipio' => '149'],
        ['name' => 'Agua Viva','municipality_id' => '251','id_municipio' => '149'],
        ['name' => 'Sarare','municipality_id' => '253','id_municipio' => '150'],
        ['name' => 'Buría','municipality_id' => '253','id_municipio' => '150'],
        ['name' => 'Gustavo Vegas León','municipality_id' => '253','id_municipio' => '150'],
        ['name' => 'Trinidad Samuel','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Antonio Díaz','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Camacaro','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Castañeda','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Cecilio Zubillaga','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Chiquinquirá','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'El Blanco','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Espinoza de los Monteros','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Lara','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Las Mercedes','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Manuel Morillo','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Montaña Verde','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Montes de Oca','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Torres','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Heriberto Arroyo','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Reyes Vargas','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Altagracia','municipality_id' => '262','id_municipio' => '151'],
        ['name' => 'Siquisique','municipality_id' => '277','id_municipio' => '152'],
        ['name' => 'Moroturo','municipality_id' => '277','id_municipio' => '152'],
        ['name' => 'San Miguel','municipality_id' => '277','id_municipio' => '152'],
        ['name' => 'Xaguas','municipality_id' => '277','id_municipio' => '152'],
        ['name' => 'Presidente Betancourt','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'Presidente Páez','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'Presidente Rómulo Gallegos','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'Gabriel Picón González','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'Héctor Amable Mora','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'José Nucete Sardi','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'Pulido Méndez','municipality_id' => '674','id_municipio' => '179'],
        ['name' => 'La Azulita','municipality_id' => '676','id_municipio' => '180'],
        ['name' => 'Santa Cruz de Mora','municipality_id' => '680','id_municipio' => '181'],
        ['name' => 'Mesa Bolívar','municipality_id' => '680','id_municipio' => '181'],
        ['name' => 'Mesa de Las Palmas','municipality_id' => '680','id_municipio' => '181'],
        ['name' => 'Aricagua','municipality_id' => '682','id_municipio' => '182'],
        ['name' => 'San Antonio','municipality_id' => '682','id_municipio' => '182'],
        ['name' => 'Canagua','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Capurí','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Chacantá','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'El Molino','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Guaimaral','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Mucutuy','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Mucuchachí','municipality_id' => '686','id_municipio' => '183'],
        ['name' => 'Fernández Peña','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'Matriz','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'Montalbán','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'Acequias','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'Jají','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'La Mesa','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'San José del Sur','municipality_id' => '687','id_municipio' => '184'],
        ['name' => 'Tucaní','municipality_id' => '691','id_municipio' => '185'],
        ['name' => 'Florencio Ramírez','municipality_id' => '691','id_municipio' => '185'],
        ['name' => 'Santo Domingo','municipality_id' => '693','id_municipio' => '186'],
        ['name' => 'Las Piedras','municipality_id' => '693','id_municipio' => '186'],
        ['name' => 'Guaraque','municipality_id' => '695','id_municipio' => '187'],
        ['name' => 'Mesa de Quintero','municipality_id' => '695','id_municipio' => '187'],
        ['name' => 'Río Negro','municipality_id' => '695','id_municipio' => '187'],
        ['name' => 'Arapuey','municipality_id' => '699','id_municipio' => '188'],
        ['name' => 'Palmira','municipality_id' => '699','id_municipio' => '188'],
        ['name' => 'San Cristóbal de Torondoy','municipality_id' => '701','id_municipio' => '189'],
        ['name' => 'Torondoy','municipality_id' => '701','id_municipio' => '189'],
        ['name' => 'Antonio Spinetti Dini','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Arias','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Caracciolo Parra Pérez','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Domingo Peña','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'El Llano','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Gonzalo Picón Febres','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Jacinto Plaza','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Juan Rodríguez Suárez','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Lasso de la Vega','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Mariano Picón Salas','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Milla','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Osuna Rodríguez','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Sagrario','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'El Morro','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Los Nevados','municipality_id' => '703','id_municipio' => '190'],
        ['name' => 'Andrés Eloy Blanco','municipality_id' => '708','id_municipio' => '191'],
        ['name' => 'La Venta','municipality_id' => '708','id_municipio' => '191'],
        ['name' => 'Piñango','municipality_id' => '708','id_municipio' => '191'],
        ['name' => 'Timotes','municipality_id' => '708','id_municipio' => '191'],
        ['name' => 'Eloy Paredes','municipality_id' => '714','id_municipio' => '192'],
        ['name' => 'San Rafael de Alcázar','municipality_id' => '714','id_municipio' => '192'],
        ['name' => 'Santa Elena de Arenales','municipality_id' => '714','id_municipio' => '192'],
        ['name' => 'Santa María de Caparo','municipality_id' => '718','id_municipio' => '193'],
        ['name' => 'Pueblo Llano','municipality_id' => '725','id_municipio' => '194'],
        ['name' => 'Cacute','municipality_id' => '730','id_municipio' => '195'],
        ['name' => 'La Toma','municipality_id' => '730','id_municipio' => '195'],
        ['name' => 'Mucuchíes','municipality_id' => '730','id_municipio' => '195'],
        ['name' => 'Mucurubá','municipality_id' => '730','id_municipio' => '195'],
        ['name' => 'San Rafael','municipality_id' => '730','id_municipio' => '195'],
        ['name' => 'Gerónimo Maldonado','municipality_id' => '738','id_municipio' => '196'],
        ['name' => 'Bailadores','municipality_id' => '738','id_municipio' => '196'],
        ['name' => 'Tabay','municipality_id' => '742','id_municipio' => '197'],
        ['name' => 'Chiguará','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'Estánquez','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'Lagunillas','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'La Trampa','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'Pueblo Nuevo del Sur','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'San Juan','municipality_id' => '748','id_municipio' => '198'],
        ['name' => 'El Amparo','municipality_id' => '754','id_municipio' => '199'],
        ['name' => 'El Llano','municipality_id' => '754','id_municipio' => '199'],
        ['name' => 'San Francisco','municipality_id' => '754','id_municipio' => '199'],
        ['name' => 'Tovar','municipality_id' => '754','id_municipio' => '199'],
        ['name' => 'Independencia','municipality_id' => '757','id_municipio' => '200'],
        ['name' => 'María de la Concepción Palacios Blanco','municipality_id' => '757','id_municipio' => '200'],
        ['name' => 'Nueva Bolivia','municipality_id' => '757','id_municipio' => '200'],
        ['name' => 'Santa Apolonia','municipality_id' => '757','id_municipio' => '200'],
        ['name' => 'Caño El Tigre','municipality_id' => '764','id_municipio' => '201'],
        ['name' => 'Zea','municipality_id' => '764','id_municipio' => '201'],
        ['name' => 'Aragüita','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Arévalo González','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Capaya','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Caucagua','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Panaquire','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Ribas','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'El Café','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Marizapa','municipality_id' => '786','id_municipio' => '223'],
        ['name' => 'Cumbo','municipality_id' => '787','id_municipio' => '224'],
        ['name' => 'San José de Barlovento','municipality_id' => '787','id_municipio' => '224'],
        ['name' => 'El Cafetal','municipality_id' => '788','id_municipio' => '225'],
        ['name' => 'Las Minas','municipality_id' => '788','id_municipio' => '225'],
        ['name' => 'Nuestra Señora del Rosario','municipality_id' => '788','id_municipio' => '225'],
        ['name' => 'Higuerote','municipality_id' => '789','id_municipio' => '226'],
        ['name' => 'Curiepe','municipality_id' => '789','id_municipio' => '226'],
        ['name' => 'Tacarigua de Brión','municipality_id' => '789','id_municipio' => '226'],
        ['name' => 'Mamporal','municipality_id' => '3265','id_municipio' => '227'],
        ['name' => 'Carrizal','municipality_id' => '3266','id_municipio' => '228'],
        ['name' => 'Chacao','municipality_id' => '3267','id_municipio' => '229'],
        ['name' => 'Charallave','municipality_id' => '3269','id_municipio' => '230'],
        ['name' => 'Las Brisas','municipality_id' => '3269','id_municipio' => '230'],
        ['name' => 'El Hatillo','municipality_id' => '3274','id_municipio' => '231'],
        ['name' => 'Altagracia de la Montaña','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'Cecilio Acosta','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'Los Teques','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'El Jarillo','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'San Pedro','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'Tácata','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'Paracotos','municipality_id' => '3279','id_municipio' => '232'],
        ['name' => 'Cartanal','municipality_id' => '3280','id_municipio' => '233'],
        ['name' => 'Santa Teresa del Tuy','municipality_id' => '3280','id_municipio' => '233'],
        ['name' => 'La Democracia','municipality_id' => '3283','id_municipio' => '234'],
        ['name' => 'Ocumare del Tuy','municipality_id' => '3283','id_municipio' => '234'],
        ['name' => 'Santa Bárbara','municipality_id' => '3283','id_municipio' => '234'],
        ['name' => 'San Antonio de los Altos','municipality_id' => '3288','id_municipio' => '235'],
        ['name' => 'Río Chico','municipality_id' => '3295','id_municipio' => '236'],
        ['name' => 'El Guapo','municipality_id' => '3295','id_municipio' => '236'],
        ['name' => 'Tacarigua de la Laguna','municipality_id' => '3295','id_municipio' => '236'],
        ['name' => 'Paparo','municipality_id' => '3295','id_municipio' => '236'],
        ['name' => 'San Fernando del Guapo','municipality_id' => '3295','id_municipio' => '236'],
        ['name' => 'Santa Lucía del Tuy','municipality_id' => '3303','id_municipio' => '237'],
        ['name' => 'Cúpira','municipality_id' => '3304','id_municipio' => '238'],
        ['name' => 'Machurucuto','municipality_id' => '3304','id_municipio' => '238'],
        ['name' => 'Guarenas','municipality_id' => '3308','id_municipio' => '239'],
        ['name' => 'San Antonio de Yare','municipality_id' => '3310','id_municipio' => '240'],
        ['name' => 'San Francisco de Yare','municipality_id' => '3310','id_municipio' => '240'],
        ['name' => 'Leoncio Martínez','municipality_id' => '3311','id_municipio' => '241'],
        ['name' => 'Petare','municipality_id' => '3311','id_municipio' => '241'],
        ['name' => 'Caucagüita','municipality_id' => '3311','id_municipio' => '241'],
        ['name' => 'Filas de Mariche','municipality_id' => '3311','id_municipio' => '241'],
        ['name' => 'La Dolorita','municipality_id' => '3311','id_municipio' => '241'],
        ['name' => 'Cúa','municipality_id' => '3312','id_municipio' => '242'],
        ['name' => 'Nueva Cúa','municipality_id' => '3312','id_municipio' => '242'],
        ['name' => 'Guatire','municipality_id' => '3313','id_municipio' => '243'],
        ['name' => 'Bolívar','municipality_id' => '3313','id_municipio' => '243'],
        ['name' => 'San Antonio de Maturín','municipality_id' => '3412','id_municipio' => '258'],
        ['name' => 'San Francisco de Maturín','municipality_id' => '3412','id_municipio' => '258'],
        ['name' => 'Aguasay','municipality_id' => '3432','id_municipio' => '259'],
        ['name' => 'Caripito','municipality_id' => '3434','id_municipio' => '260'],
        ['name' => 'El Guácharo','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'La Guanota','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'Sabana de Piedra','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'San Agustín','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'Teresen','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'Caripe','municipality_id' => '3435','id_municipio' => '261'],
        ['name' => 'Areo','municipality_id' => '3436','id_municipio' => '262'],
        ['name' => 'Capital Cedeño','municipality_id' => '3436','id_municipio' => '262'],
        ['name' => 'San Félix de Cantalicio','municipality_id' => '3436','id_municipio' => '262'],
        ['name' => 'Viento Fresco','municipality_id' => '3436','id_municipio' => '262'],
        ['name' => 'El Tejero','municipality_id' => '3437','id_municipio' => '263'],
        ['name' => 'Punta de Mata','municipality_id' => '3437','id_municipio' => '263'],
        ['name' => 'Chaguaramas','municipality_id' => '3438','id_municipio' => '264'],
        ['name' => 'Las Alhuacas','municipality_id' => '3438','id_municipio' => '264'],
        ['name' => 'Tabasca','municipality_id' => '3438','id_municipio' => '264'],
        ['name' => 'Temblador','municipality_id' => '3438','id_municipio' => '264'],
        ['name' => 'Alto de los Godos','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'Boquerón','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'Las Cocuizas','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'La Cruz','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'San Simón','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'El Corozo','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'El Furrial','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'Jusepín','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'La Pica','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'San Vicente','municipality_id' => '3439','id_municipio' => '265'],
        ['name' => 'Aparicio','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'Aragua de Maturín','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'Chaguamal','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'El Pinto','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'Guanaguana','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'La Toscana','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'Taguaya','municipality_id' => '3440','id_municipio' => '266'],
        ['name' => 'Cachipo','municipality_id' => '3441','id_municipio' => '267'],
        ['name' => 'Quiriquire','municipality_id' => '3441','id_municipio' => '267'],
        ['name' => 'Santa Bárbara','municipality_id' => '3442','id_municipio' => '268'],
        ['name' => 'Barrancas','municipality_id' => '3443','id_municipio' => '269'],
        ['name' => 'Los Barrancos de Fajardo','municipality_id' => '3443','id_municipio' => '269'],
        ['name' => 'Uracoa','municipality_id' => '3445','id_municipio' => '270'],
        ['name' => 'Antolín del Campo','municipality_id' => '3455','id_municipio' => '271'],
        ['name' => 'Arismendi','municipality_id' => '3459','id_municipio' => '272'],
        ['name' => 'García','municipality_id' => '3463','id_municipio' => '273'],
        ['name' => 'Francisco Fajardo','municipality_id' => '3463','id_municipio' => '273'],
        ['name' => 'Bolívar','municipality_id' => '3466','id_municipio' => '274'],
        ['name' => 'Guevara','municipality_id' => '3466','id_municipio' => '274'],
        ['name' => 'Matasiete','municipality_id' => '3466','id_municipio' => '274'],
        ['name' => 'Santa Ana','municipality_id' => '3466','id_municipio' => '274'],
        ['name' => 'Sucre','municipality_id' => '3466','id_municipio' => '274'],
        ['name' => 'Aguirre','municipality_id' => '3473','id_municipio' => '275'],
        ['name' => 'Maneiro','municipality_id' => '3473','id_municipio' => '275'],
        ['name' => 'Adrián','municipality_id' => '3475','id_municipio' => '276'],
        ['name' => 'Juan Griego','municipality_id' => '3475','id_municipio' => '276'],
        ['name' => 'Yaguaraparo','municipality_id' => '3475','id_municipio' => '276'],
        ['name' => 'Porlamar','municipality_id' => '3479','id_municipio' => '277'],
        ['name' => 'San Francisco de Macanao','municipality_id' => '3482','id_municipio' => '278'],
        ['name' => 'Boca de Río','municipality_id' => '3482','id_municipio' => '278'],
        ['name' => 'Tubores','municipality_id' => '3485','id_municipio' => '279'],
        ['name' => 'Los Baleales','municipality_id' => '3485','id_municipio' => '279'],
        ['name' => 'Vicente Fuentes','municipality_id' => '3487','id_municipio' => '280'],
        ['name' => 'Villalba','municipality_id' => '3487','id_municipio' => '280'],
        ['name' => 'San Juan Bautista','municipality_id' => '3488','id_municipio' => '281'],
        ['name' => 'Zabala','municipality_id' => '3488','id_municipio' => '281'],
        ['name' => 'Capital Araure','municipality_id' => '3490','id_municipio' => '283'],
        ['name' => 'Río Acarigua','municipality_id' => '3490','id_municipio' => '283'],
        ['name' => 'Capital Esteller','municipality_id' => '3491','id_municipio' => '284'],
        ['name' => 'Uveral','municipality_id' => '3491','id_municipio' => '284'],
        ['name' => 'Guanare','municipality_id' => '3492','id_municipio' => '285'],
        ['name' => 'Córdoba','municipality_id' => '3492','id_municipio' => '285'],
        ['name' => 'San José de la Montaña','municipality_id' => '3492','id_municipio' => '285'],
        ['name' => 'San Juan de Guanaguanare','municipality_id' => '3492','id_municipio' => '285'],
        ['name' => 'Virgen de la Coromoto','municipality_id' => '3492','id_municipio' => '285'],
        ['name' => 'Guanarito','municipality_id' => '3493','id_municipio' => '286'],
        ['name' => 'Trinidad de la Capilla','municipality_id' => '3493','id_municipio' => '286'],
        ['name' => 'Divina Pastora','municipality_id' => '3493','id_municipio' => '286'],
        ['name' => 'Monseñor José Vicente de Unda','municipality_id' => '3494','id_municipio' => '287'],
        ['name' => 'Peña Blanca','municipality_id' => '3494','id_municipio' => '287'],
        ['name' => 'Capital Ospino','municipality_id' => '3495','id_municipio' => '288'],
        ['name' => 'Aparición','municipality_id' => '3495','id_municipio' => '288'],
        ['name' => 'La Estación','municipality_id' => '3495','id_municipio' => '288'],
        ['name' => 'Páez','municipality_id' => '3496','id_municipio' => '289'],
        ['name' => 'Payara','municipality_id' => '3496','id_municipio' => '289'],
        ['name' => 'Pimpinela','municipality_id' => '3496','id_municipio' => '289'],
        ['name' => 'Ramón Peraza','municipality_id' => '3496','id_municipio' => '289'],
        ['name' => 'Papelón','municipality_id' => '3498','id_municipio' => '290'],
        ['name' => 'Caño Delgadito','municipality_id' => '3498','id_municipio' => '290'],
        ['name' => 'San Genaro de Boconoito','municipality_id' => '3499','id_municipio' => '291'],
        ['name' => 'Antolín Tovar','municipality_id' => '3499','id_municipio' => '291'],
        ['name' => 'San Rafael de Onoto','municipality_id' => '3500','id_municipio' => '292'],
        ['name' => 'Santa Fe','municipality_id' => '3500','id_municipio' => '292'],
        ['name' => 'Thermo Morles','municipality_id' => '3500','id_municipio' => '292'],
        ['name' => 'Santa Rosalía','municipality_id' => '3501','id_municipio' => '293'],
        ['name' => 'Florida','municipality_id' => '3501','id_municipio' => '293'],
        ['name' => 'Sucre','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'Concepción','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'San Rafael de Palo Alzado','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'Uvencio Antonio Velásquez','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'San José de Saguaz','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'Villa Rosa','municipality_id' => '3502','id_municipio' => '294'],
        ['name' => 'Turén','municipality_id' => '3503','id_municipio' => '295'],
        ['name' => 'Canelones','municipality_id' => '3503','id_municipio' => '295'],
        ['name' => 'Santa Cruz','municipality_id' => '3503','id_municipio' => '295'],
        ['name' => 'San Isidro Labrador','municipality_id' => '3503','id_municipio' => '295'],
        ['name' => 'Mariño','municipality_id' => '3504','id_municipio' => '296'],
        ['name' => 'Rómulo Gallegos','municipality_id' => '3504','id_municipio' => '296'],
        ['name' => 'San José de Aerocuar','municipality_id' => '3505','id_municipio' => '297'],
        ['name' => 'Tavera Acosta','municipality_id' => '3505','id_municipio' => '297'],
        ['name' => 'Río Caribe','municipality_id' => '3506','id_municipio' => '298'],
        ['name' => 'Antonio José de Sucre','municipality_id' => '3506','id_municipio' => '298'],
        ['name' => 'El Morro de Puerto Santo','municipality_id' => '3506','id_municipio' => '298'],
        ['name' => 'Puerto Santo','municipality_id' => '3506','id_municipio' => '298'],
        ['name' => 'San Juan de las Galdonas','municipality_id' => '3506','id_municipio' => '298'],
        ['name' => 'El Pilar','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'El Rincón','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'General Francisco Antonio Váquez','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'Guaraúnos','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'Tunapuicito','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'Unión','municipality_id' => '3507','id_municipio' => '299'],
        ['name' => 'Santa Catalina','municipality_id' => '3510','id_municipio' => '300'],
        ['name' => 'Santa Rosa','municipality_id' => '3510','id_municipio' => '300'],
        ['name' => 'Santa Teresa','municipality_id' => '3510','id_municipio' => '300'],
        ['name' => 'Bolívar','municipality_id' => '3510','id_municipio' => '300'],
        ['name' => 'Maracapana','municipality_id' => '3510','id_municipio' => '300'],
        ['name' => 'Libertad','municipality_id' => '3512','id_municipio' => '302'],
        ['name' => 'El Paujil','municipality_id' => '3512','id_municipio' => '302'],
        ['name' => 'Yaguaraparo','municipality_id' => '3512','id_municipio' => '302'],
        ['name' => 'Cruz Salmerón Acosta','municipality_id' => '3513','id_municipio' => '303'],
        ['name' => 'Chacopata','municipality_id' => '3513','id_municipio' => '303'],
        ['name' => 'Manicuare','municipality_id' => '3513','id_municipio' => '303'],
        ['name' => 'Tunapuy','municipality_id' => '3514','id_municipio' => '304'],
        ['name' => 'Campo Elías','municipality_id' => '3514','id_municipio' => '304'],
        ['name' => 'Irapa','municipality_id' => '3515','id_municipio' => '305'],
        ['name' => 'Campo Claro','municipality_id' => '3515','id_municipio' => '305'],
        ['name' => 'Maraval','municipality_id' => '3515','id_municipio' => '305'],
        ['name' => 'San Antonio de Irapa','municipality_id' => '3515','id_municipio' => '305'],
        ['name' => 'Soro','municipality_id' => '3515','id_municipio' => '305'],
        ['name' => 'Mejía','municipality_id' => '3516','id_municipio' => '306'],
        ['name' => 'Cumanacoa','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'Arenas','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'Aricagua','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'Cogollar','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'San Fernando','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'San Lorenzo','municipality_id' => '3517','id_municipio' => '307'],
        ['name' => 'Villa Frontado (Muelle de Cariaco)','municipality_id' => '3518','id_municipio' => '308'],
        ['name' => 'Catuaro','municipality_id' => '3518','id_municipio' => '308'],
        ['name' => 'Rendón','municipality_id' => '3518','id_municipio' => '308'],
        ['name' => 'San Cruz','municipality_id' => '3518','id_municipio' => '308'],
        ['name' => 'Santa María','municipality_id' => '3518','id_municipio' => '308'],
        ['name' => 'Altagracia','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Santa Inés','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Valentín Valiente','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Ayacucho','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'San Juan','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Raúl Leoni','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Gran Mariscal','municipality_id' => '3519','id_municipio' => '309'],
        ['name' => 'Cristóbal Colón','municipality_id' => '3521','id_municipio' => '310'],
        ['name' => 'Bideau','municipality_id' => '3521','id_municipio' => '310'],
        ['name' => 'Punta de Piedras','municipality_id' => '3521','id_municipio' => '310'],
        ['name' => 'Güiria','municipality_id' => '3521','id_municipio' => '310'],
        ['name' => 'Andrés Bello','municipality_id' => '3525','id_municipio' => '341'],
        ['name' => 'Antonio Rómulo Costa','municipality_id' => '3526','id_municipio' => '342'],
        ['name' => 'Ayacucho','municipality_id' => '3527','id_municipio' => '343'],
        ['name' => 'Rivas Berti','municipality_id' => '3527','id_municipio' => '343'],
        ['name' => 'San Pedro del Río','municipality_id' => '3527','id_municipio' => '343'],
        ['name' => 'Bolívar','municipality_id' => '3528','id_municipio' => '344'],
        ['name' => 'Palotal','municipality_id' => '3528','id_municipio' => '344'],
        ['name' => 'General Juan Vicente Gómez','municipality_id' => '3528','id_municipio' => '344'],
        ['name' => 'Isaías Medina Angarita','municipality_id' => '3528','id_municipio' => '344'],
        ['name' => 'Cárdenas','municipality_id' => '3529','id_municipio' => '345'],
        ['name' => 'Amenodoro Ángel Lamus','municipality_id' => '3529','id_municipio' => '345'],
        ['name' => 'La Florida','municipality_id' => '3529','id_municipio' => '345'],
        ['name' => 'Córdoba','municipality_id' => '3530','id_municipio' => '346'],
        ['name' => 'Fernández Feo','municipality_id' => '3531','id_municipio' => '347'],
        ['name' => 'Alberto Adriani','municipality_id' => '3531','id_municipio' => '347'],
        ['name' => 'Santo Domingo','municipality_id' => '3531','id_municipio' => '347'],
        ['name' => 'Francisco de Miranda','municipality_id' => '3532','id_municipio' => '348'],
        ['name' => 'García de Hevia','municipality_id' => '3533','id_municipio' => '349'],
        ['name' => 'Boca de Grita','municipality_id' => '3533','id_municipio' => '349'],
        ['name' => 'José Antonio Páez','municipality_id' => '3533','id_municipio' => '349'],
        ['name' => 'Guásimos','municipality_id' => '3535','id_municipio' => '350'],
        ['name' => 'Independencia','municipality_id' => '3536','id_municipio' => '351'],
        ['name' => 'Juan Germán Roscio','municipality_id' => '3536','id_municipio' => '351'],
        ['name' => 'Román Cárdenas','municipality_id' => '3536','id_municipio' => '351'],
        ['name' => 'Jáuregui','municipality_id' => '3537','id_municipio' => '352'],
        ['name' => 'Emilio Constantino Guerrero','municipality_id' => '3537','id_municipio' => '352'],
        ['name' => 'Monseñor Miguel Antonio Salas','municipality_id' => '3537','id_municipio' => '352'],
        ['name' => 'José María Vargas','municipality_id' => '3538','id_municipio' => '353'],
        ['name' => 'Junín','municipality_id' => '3539','id_municipio' => '354'],
        ['name' => 'La Petrólea','municipality_id' => '3539','id_municipio' => '354'],
        ['name' => 'Quinimarí','municipality_id' => '3539','id_municipio' => '354'],
        ['name' => 'Bramón','municipality_id' => '3539','id_municipio' => '354'],
        ['name' => 'Libertad','municipality_id' => '3540','id_municipio' => '355'],
        ['name' => 'Cipriano Castro','municipality_id' => '3540','id_municipio' => '355'],
        ['name' => 'Manuel Felipe Rugeles','municipality_id' => '3540','id_municipio' => '355'],
        ['name' => 'Libertador','municipality_id' => '3541','id_municipio' => '356'],
        ['name' => 'Doradas','municipality_id' => '3541','id_municipio' => '356'],
        ['name' => 'Emeterio Ochoa','municipality_id' => '3541','id_municipio' => '356'],
        ['name' => 'San Joaquín de Navay','municipality_id' => '3541','id_municipio' => '356'],
        ['name' => 'Lobatera','municipality_id' => '3542','id_municipio' => '357'],
        ['name' => 'Constitución','municipality_id' => '3542','id_municipio' => '357'],
        ['name' => 'Michelena','municipality_id' => '3543','id_municipio' => '358'],
        ['name' => 'Panamericano','municipality_id' => '3544','id_municipio' => '359'],
        ['name' => 'La Palmita','municipality_id' => '3544','id_municipio' => '359'],
        ['name' => 'Pedro María Ureña','municipality_id' => '3546','id_municipio' => '360'],
        ['name' => 'Nueva Arcadia','municipality_id' => '3546','id_municipio' => '360'],
        ['name' => 'Delicias','municipality_id' => '3547','id_municipio' => '361'],
        ['name' => 'Pecaya','municipality_id' => '3547','id_municipio' => '361'],
        ['name' => 'Samuel Darío Maldonado','municipality_id' => '3548','id_municipio' => '362'],
        ['name' => 'Boconó','municipality_id' => '3548','id_municipio' => '362'],
        ['name' => 'Hernández','municipality_id' => '3548','id_municipio' => '362'],
        ['name' => 'La Concordia','municipality_id' => '3549','id_municipio' => '363'],
        ['name' => 'San Juan Bautista','municipality_id' => '3549','id_municipio' => '363'],
        ['name' => 'Pedro María Morantes','municipality_id' => '3549','id_municipio' => '363'],
        ['name' => 'San Sebastián','municipality_id' => '3549','id_municipio' => '363'],
        ['name' => 'Dr. Francisco Romero Lobo','municipality_id' => '3549','id_municipio' => '363'],
        ['name' => 'Seboruco','municipality_id' => '3550','id_municipio' => '364'],
        ['name' => 'Simón Rodríguez','municipality_id' => '3551','id_municipio' => '365'],
        ['name' => 'Sucre','municipality_id' => '3552','id_municipio' => '366'],
        ['name' => 'Eleazar López Contreras','municipality_id' => '3552','id_municipio' => '366'],
        ['name' => 'San Pablo','municipality_id' => '3552','id_municipio' => '366'],
        ['name' => 'Torbes','municipality_id' => '3553','id_municipio' => '367'],
        ['name' => 'Uribante','municipality_id' => '3554','id_municipio' => '368'],
        ['name' => 'Cárdenas','municipality_id' => '3554','id_municipio' => '368'],
        ['name' => 'Juan Pablo Peñalosa','municipality_id' => '3554','id_municipio' => '368'],
        ['name' => 'Potosí','municipality_id' => '3554','id_municipio' => '368'],
        ['name' => 'San Judas Tadeo','municipality_id' => '3555','id_municipio' => '369'],
        ['name' => 'Araguaney','municipality_id' => '3557','id_municipio' => '370'],
        ['name' => 'El Jaguito','municipality_id' => '3557','id_municipio' => '370'],
        ['name' => 'La Esperanza','municipality_id' => '3557','id_municipio' => '370'],
        ['name' => 'Santa Isabel','municipality_id' => '3557','id_municipio' => '370'],
        ['name' => 'Boconó','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'El Carmen','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Mosquey','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Ayacucho','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Burbusay','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'General Ribas','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Guaramacal','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Vega de Guaramacal','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Monseñor Jáuregui','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Rafael Rangel','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'San Miguel','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'San José','municipality_id' => '3558','id_municipio' => '371'],
        ['name' => 'Sabana Grande','municipality_id' => '3559','id_municipio' => '372'],
        ['name' => 'Cheregüé','municipality_id' => '3559','id_municipio' => '372'],
        ['name' => 'Granados','municipality_id' => '3559','id_municipio' => '372'],
        ['name' => 'Arnoldo Gabaldón','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Bolivia','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Carrillo','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Cegarra','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Chejendé','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Manuel Salvador Ulloa','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'San José','municipality_id' => '3560','id_municipio' => '373'],
        ['name' => 'Carache','municipality_id' => '3561','id_municipio' => '374'],
        ['name' => 'La Concepción','municipality_id' => '3561','id_municipio' => '374'],
        ['name' => 'Cuicas','municipality_id' => '3561','id_municipio' => '374'],
        ['name' => 'Panamericana','municipality_id' => '3561','id_municipio' => '374'],
        ['name' => 'Santa Cruz','municipality_id' => '3561','id_municipio' => '374'],
        ['name' => 'Escuque','municipality_id' => '3562','id_municipio' => '375'],
        ['name' => 'La Unión','municipality_id' => '3562','id_municipio' => '375'],
        ['name' => 'Santa Rita','municipality_id' => '3562','id_municipio' => '375'],
        ['name' => 'Sabana Libre','municipality_id' => '3562','id_municipio' => '375'],
        ['name' => 'El Socorro','municipality_id' => '3563','id_municipio' => '376'],
        ['name' => 'Los Caprichos','municipality_id' => '3563','id_municipio' => '376'],
        ['name' => 'Antonio José de Sucre','municipality_id' => '3563','id_municipio' => '376'],
        ['name' => 'Campo Elías','municipality_id' => '3564','id_municipio' => '377'],
        ['name' => 'Arnoldo Gabaldón','municipality_id' => '3564','id_municipio' => '377'],
        ['name' => 'Santa Apolonia','municipality_id' => '3565','id_municipio' => '378'],
        ['name' => 'El Progreso','municipality_id' => '3565','id_municipio' => '378'],
        ['name' => 'La Ceiba','municipality_id' => '3565','id_municipio' => '378'],
        ['name' => 'Tres de Febrero','municipality_id' => '3565','id_municipio' => '378'],
        ['name' => 'El Dividive','municipality_id' => '3566','id_municipio' => '379'],
        ['name' => 'Agua Santa','municipality_id' => '3566','id_municipio' => '379'],
        ['name' => 'Agua Caliente','municipality_id' => '3566','id_municipio' => '379'],
        ['name' => 'El Cenizo','municipality_id' => '3566','id_municipio' => '379'],
        ['name' => 'Valerita','municipality_id' => '3566','id_municipio' => '379'],
        ['name' => 'Monte Carmelo','municipality_id' => '3568','id_municipio' => '380'],
        ['name' => 'Buena Vista','municipality_id' => '3568','id_municipio' => '380'],
        ['name' => 'Santa María del Horcón','municipality_id' => '3568','id_municipio' => '380'],
        ['name' => 'Motatán','municipality_id' => '3569','id_municipio' => '381'],
        ['name' => 'El Baño','municipality_id' => '3569','id_municipio' => '381'],
        ['name' => 'Jalisco','municipality_id' => '3569','id_municipio' => '381'],
        ['name' => 'Pampán','municipality_id' => '3570','id_municipio' => '382'],
        ['name' => 'Flor de Patria','municipality_id' => '3570','id_municipio' => '382'],
        ['name' => 'La Paz','municipality_id' => '3570','id_municipio' => '382'],
        ['name' => 'Santa Ana','municipality_id' => '3570','id_municipio' => '382'],
        ['name' => 'Pampanito','municipality_id' => '3571','id_municipio' => '383'],
        ['name' => 'La Concepción','municipality_id' => '3571','id_municipio' => '383'],
        ['name' => 'Pampanito II','municipality_id' => '3571','id_municipio' => '383'],
        ['name' => 'Betijoque','municipality_id' => '3572','id_municipio' => '384'],
        ['name' => 'José Gregorio Hernández','municipality_id' => '3572','id_municipio' => '384'],
        ['name' => 'La Pueblita','municipality_id' => '3572','id_municipio' => '384'],
        ['name' => 'Los Cedros','municipality_id' => '3572','id_municipio' => '384'],
        ['name' => 'Carvajal','municipality_id' => '3573','id_municipio' => '385'],
        ['name' => 'Campo Alegre','municipality_id' => '3573','id_municipio' => '385'],
        ['name' => 'Antonio Nicolás Briceño','municipality_id' => '3573','id_municipio' => '385'],
        ['name' => 'José Leonardo Suárez','municipality_id' => '3573','id_municipio' => '385'],
        ['name' => 'Sabana de Mendoza','municipality_id' => '3574','id_municipio' => '386'],
        ['name' => 'Junín','municipality_id' => '3574','id_municipio' => '386'],
        ['name' => 'Valmore Rodríguez','municipality_id' => '3574','id_municipio' => '386'],
        ['name' => 'El Paraíso','municipality_id' => '3574','id_municipio' => '386'],
        ['name' => 'Andrés Linares','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Chiquinquirá','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Cristóbal Mendoza','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Cruz Carrillo','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Matriz','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Monseñor Carrillo','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Tres Esquinas','municipality_id' => '3575','id_municipio' => '387'],
        ['name' => 'Cabimbú','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'Jajó','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'La Mesa de Esnujaque','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'Santiago','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'Tuñame','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'La Quebrada','municipality_id' => '3576','id_municipio' => '388'],
        ['name' => 'Juan Ignacio Montilla','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'La Beatriz','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'La Puerta','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'Mendoza del Valle de Momboy','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'Mercedes Díaz','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'San Luis','municipality_id' => '3577','id_municipio' => '389'],
        ['name' => 'Caraballeda','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Carayaca','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Carlos Soublette','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Caruao Chuspa','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Catia La Mar','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'El Junko','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'La Guaira','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Macuto','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Maiquetía','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Naiguatá','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Urimare','municipality_id' => '3579','id_municipio' => '390'],
        ['name' => 'Arístides Bastidas','municipality_id' => '3580','id_municipio' => '391'],
        ['name' => 'Bolívar','municipality_id' => '3581','id_municipio' => '392'],
        ['name' => 'Chivacoa','municipality_id' => '3584','id_municipio' => '407'],
        ['name' => 'Campo Elías','municipality_id' => '3584','id_municipio' => '407'],
        ['name' => 'Cocorote','municipality_id' => '3585','id_municipio' => '408'],
        ['name' => 'Independencia','municipality_id' => '3586','id_municipio' => '409'],
        ['name' => 'José Antonio Páez','municipality_id' => '3588','id_municipio' => '410'],
        ['name' => 'La Trinidad','municipality_id' => '3596','id_municipio' => '411'],
        ['name' => 'Manuel Monge','municipality_id' => '3598','id_municipio' => '412'],
        ['name' => 'Salóm','municipality_id' => '3602','id_municipio' => '413'],
        ['name' => 'Temerla','municipality_id' => '3602','id_municipio' => '413'],
        ['name' => 'Nirgua','municipality_id' => '3602','id_municipio' => '413'],
        ['name' => 'San Andrés','municipality_id' => '3610','id_municipio' => '414'],
        ['name' => 'Yaritagua','municipality_id' => '3610','id_municipio' => '414'],
        ['name' => 'San Javier','municipality_id' => '3612','id_municipio' => '415'],
        ['name' => 'Albarico','municipality_id' => '3612','id_municipio' => '415'],
        ['name' => 'San Felipe','municipality_id' => '3612','id_municipio' => '415'],
        ['name' => 'Sucre','municipality_id' => '3619','id_municipio' => '416'],
        ['name' => 'Urachiche','municipality_id' => '3624','id_municipio' => '417'],
        ['name' => 'El Guayabo','municipality_id' => '3629','id_municipio' => '418'],
        ['name' => 'Farriar','municipality_id' => '3629','id_municipio' => '418'],
        ['name' => 'Isla de Toas','municipality_id' => '3642','id_municipio' => '441'],
        ['name' => 'Monagas','municipality_id' => '3642','id_municipio' => '441'],
        ['name' => 'San Timoteo','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'General Urdaneta','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'Libertador','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'Marcelino Briceño','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'Pueblo Nuevo','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'Manuel Guanipa Matos','municipality_id' => '3644','id_municipio' => '442'],
        ['name' => 'Ambrosio','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Carmen Herrera','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'La Rosa','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Germán Ríos Linares','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'San Benito','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Rómulo Betancourt','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Jorge Hernández','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Punta Gorda','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Arístides Calvani','municipality_id' => '3646','id_municipio' => '443'],
        ['name' => 'Encontrados','municipality_id' => '3648','id_municipio' => '444'],
        ['name' => 'Udón Pérez','municipality_id' => '3648','id_municipio' => '444'],
        ['name' => 'Moralito','municipality_id' => '3651','id_municipio' => '445'],
        ['name' => 'San Carlos del Zulia','municipality_id' => '3651','id_municipio' => '445'],
        ['name' => 'Santa Cruz del Zulia','municipality_id' => '3651','id_municipio' => '445'],
        ['name' => 'Santa Bárbara','municipality_id' => '3651','id_municipio' => '445'],
        ['name' => 'Urribarrí','municipality_id' => '3651','id_municipio' => '445'],
        ['name' => 'Carlos Quevedo','municipality_id' => '3653','id_municipio' => '446'],
        ['name' => 'Francisco Javier Pulgar','municipality_id' => '3653','id_municipio' => '446'],
        ['name' => 'Simón Rodríguez','municipality_id' => '3653','id_municipio' => '446'],
        ['name' => 'Guamo-Gavilanes','municipality_id' => '3653','id_municipio' => '446'],
        ['name' => 'La Concepción','municipality_id' => '3656','id_municipio' => '448'],
        ['name' => 'San José','municipality_id' => '3656','id_municipio' => '448'],
        ['name' => 'Mariano Parra León','municipality_id' => '3656','id_municipio' => '448'],
        ['name' => 'José Ramón Yépez','municipality_id' => '3656','id_municipio' => '448'],
        ['name' => 'Jesús María Semprún','municipality_id' => '3660','id_municipio' => '449'],
        ['name' => 'Barí','municipality_id' => '3660','id_municipio' => '449'],
        ['name' => 'Concepción','municipality_id' => '3662','id_municipio' => '450'],
        ['name' => 'Andrés Bello','municipality_id' => '3662','id_municipio' => '450'],
        ['name' => 'Chiquinquirá','municipality_id' => '3662','id_municipio' => '450'],
        ['name' => 'El Carmelo','municipality_id' => '3662','id_municipio' => '450'],
        ['name' => 'Potreritos','municipality_id' => '3662','id_municipio' => '450'],
        ['name' => 'Libertad','municipality_id' => '3663','id_municipio' => '451'],
        ['name' => 'Alonso de Ojeda','municipality_id' => '3663','id_municipio' => '451'],
        ['name' => 'Venezuela','municipality_id' => '3663','id_municipio' => '451'],
        ['name' => 'Eleazar López Contreras','municipality_id' => '3663','id_municipio' => '451'],
        ['name' => 'Campo Lara','municipality_id' => '3663','id_municipio' => '451'],
        ['name' => 'Bartolomé de las Casas','municipality_id' => '3664','id_municipio' => '452'],
        ['name' => 'Libertad','municipality_id' => '3664','id_municipio' => '452'],
        ['name' => 'Río Negro','municipality_id' => '3664','id_municipio' => '452'],
        ['name' => 'San José de Perijá','municipality_id' => '3664','id_municipio' => '452'],
        ['name' => 'San Rafael','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'La Sierrita','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Las Parcelas','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Luis de Vicente','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Monseñor Marcos Sergio Godoy','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Ricaurte','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Tamare','municipality_id' => '3665','id_municipio' => '453'],
        ['name' => 'Antonio Borjas Romero','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Bolívar','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Cacique Mara','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Carracciolo Parra Pérez','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Cecilio Acosta','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Cristo de Aranza','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Coquivacoa','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Chiquinquirá','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Francisco Eugenio Bustamante','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Idelfonzo Vásquez','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Juana de Ávila','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Luis Hurtado Higuera','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Manuel Dagnino','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Olegario Villalobos','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Raúl Leoni','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Santa Lucía','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Venancio Pulgar','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'San Isidro','municipality_id' => '3666','id_municipio' => '454'],
        ['name' => 'Altagracia','municipality_id' => '3667','id_municipio' => '455'],
        ['name' => 'Faría','municipality_id' => '3667','id_municipio' => '455'],
        ['name' => 'Ana María Campos','municipality_id' => '3667','id_municipio' => '455'],
        ['name' => 'San Antonio','municipality_id' => '3667','id_municipio' => '455'],
        ['name' => 'San José','municipality_id' => '3667','id_municipio' => '455'],
        ['name' => 'Donaldo García','municipality_id' => '3668','id_municipio' => '456'],
        ['name' => 'El Rosario','municipality_id' => '3668','id_municipio' => '456'],
        ['name' => 'Sixto Zambrano','municipality_id' => '3668','id_municipio' => '456'],
        ['name' => 'San Francisco','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'El Bajo','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'Domitila Flores','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'Francisco Ochoa','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'Los Cortijos','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'Marcial Hernández','municipality_id' => '3669','id_municipio' => '457'],
        ['name' => 'Santa Rita','municipality_id' => '3670','id_municipio' => '458'],
        ['name' => 'El Mene','municipality_id' => '3670','id_municipio' => '458'],
        ['name' => 'Pedro Lucas Urribarrí','municipality_id' => '3670','id_municipio' => '458'],
        ['name' => 'José Cenobio Urribarrí','municipality_id' => '3670','id_municipio' => '458'],
        ['name' => 'Rafael Maria Baralt','municipality_id' => '3671','id_municipio' => '459'],
        ['name' => 'Manuel Manrique','municipality_id' => '3671','id_municipio' => '459'],
        ['name' => 'Rafael Urdaneta','municipality_id' => '3671','id_municipio' => '459'],
        ['name' => 'Bobures','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'Gibraltar','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'Heras','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'Monseñor Arturo Álvarez','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'Rómulo Gallegos','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'El Batey','municipality_id' => '3673','id_municipio' => '460'],
        ['name' => 'Rafael Urdaneta','municipality_id' => '3674','id_municipio' => '461'],
        ['name' => 'La Victoria','municipality_id' => '3674','id_municipio' => '461'],
        ['name' => 'Raúl Cuenca','municipality_id' => '3674','id_municipio' => '461'],
        ['name' => 'Sinamaica','municipality_id' => '3655','id_municipio' => '447'],
        ['name' => 'Alta Guajira','municipality_id' => '3655','id_municipio' => '447'],
        ['name' => 'Elías Sánchez Rubio','municipality_id' => '3655','id_municipio' => '447'],
        ['name' => 'Guajira','municipality_id' => '3655','id_municipio' => '447'],
        ['name' => 'Altagracia','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Antímano','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Caricuao','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Catedral','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Coche','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'El Junquito','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'El Paraíso','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'El Recreo','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'El Valle','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'La Candelaria','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'La Pastora','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'La Vega','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Macarao','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'San Agustín','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'San Bernardino','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'San José','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'San Juan','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'San Pedro','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Santa Rosalía','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Santa Teresa','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => 'Sucre (Catia)','municipality_id' => '3675','id_municipio' => '462'],
        ['name' => '23 de enero','municipality_id' => '3675','id_municipio' => '462']
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->parishesArray as $value) {
            Parish::create($value);
        }
    }   
}
